### ISSUE TITLE
13. Adding a Route for Comments

### ISSUE THREAD

**Issue by phylliswong** [MakeSchool-Tutorials/Node-Rotten-Potatoes#10]
Please explain the bug you found here.
import comments from 'comments; 
seems to be a very pythonic way to bring modules into a file
nodemon shows this error:
<img width="623" alt="screen shot 2018-09-05 at 10 07 39 am" src="https://user-images.githubusercontent.com/24304039/45109175-92215680-b0f3-11e8-940d-3db3373cc53d.png">

**Comment by ajbraus** [comment]
Fixed! downgraded from ES6 modules to ES5 modules. Node is not quite there yet.

**Comment by ajbraus** [comment]
```js
module.exports = (app) => {

}
```
