### ISSUE TITLE
3. Adding a MongoDB Database to Your App

### ISSUE THREAD

**Issue by phylliswong** [MakeSchool-Tutorials/Node-Rotten-Potatoes#11]
Please explain the bug you found here.
this tutorial skips where the data/db folder needs to be placed. 
I figured out it has to be placed at the lowest level directory, but that was not clear in the tutorial. Perhaps some instructions about cd'ing into the lowest level from the user home directory would be helpful.

**Comment by ajbraus** [comment]
if you type 

```
mkdir -p /data/db
```

anywhere it will put it in the root. I think the `-p` tag means "absolute path".

Added the permissions command as well

```
sudo chown -R $USER /data/db 
```
