### ISSUE TITLE
5. Show Route: See One Resource

### ISSUE THREAD

**Issue by thecodingsophist** [MakeSchool-Tutorials/Node-Rotten-Potatoes#12]
Please explain the bug you found here.

Note the use of 'back ticks' for string interpolation for ${review._id}. 

Instead of single or double quotes, use `` for string interpolation.

**Comment by ajbraus** [comment]
Hmm I don't know what you mean. Here's the docs on string interpolation
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
