### ISSUE TITLE
8. Adding Tests

### ISSUE THREAD

**Issue by RaymondDashWu** [MakeSchool-Tutorials/Node-Rotten-Potatoes#13]
- const server = require('../server');
server file does not exist. Should be ../app

- No module.export at the end of app.js file to make testing function work

**Comment by noltron000** [comment]
This issue is related to [Issue #3](https://github.com/MakeSchool-Tutorials/Node-Rotten-Potatoes/issues/3)

The module.export is included this way

**Comment by ajbraus** [comment]
Fixed
