### ISSUE TITLE
3. Adding a MongoDB Database to Your App

### ISSUE THREAD

**Issue by jayceazua** [MakeSchool-Tutorials/Node-Rotten-Potatoes#15]
Replace: 
```mongoose.connect(dbURI, { useMongoClient: true });``` 
with 
``` mongoose.connect(dbURI, { useNewUrlParser: true }); ```

WARNING:
The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
ERROR:
(node:78947) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass opti
on { useNewUrlParser: true } to MongoClient.connect.

**Comment by ibirnam** [comment]
Good call, fixed in 0a789a29ff68f649e0fd27bef344f594e2c85609
