### ISSUE TITLE
7. Delete Route: Destroying a Resource

### ISSUE THREAD

**Issue by jayceazua** [MakeSchool-Tutorials/Node-Rotten-Potatoes#22]
```findByIdAndRemove()``` is another Deprecated way of doing things.
```(node:81063) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.```

**Comment by ibirnam** [comment]
Issue with Mongoose that they fixed on their end with an update
