### ISSUE TITLE
8. Adding Tests

### ISSUE THREAD

**Issue by jayceazua** [MakeSchool-Tutorials/Node-Rotten-Potatoes#23]
```
$ npm install -g mocha
$ npm install --save chai chai-http
```
Is not the proper way of adding testing modules into your project. `---save-dev`
Which is better practice and learning convention.

**Comment by ibirnam** [comment]
great suggestion, added in 4dcbdfdd448cd81f06f9c34505d65a1e9a29a2a2 and will incorporate that into other tutorials as well!
