### ISSUE TITLE
12. Adding a Route for Comments

### ISSUE THREAD

**Issue by alishalabi** [MakeSchool-Tutorials/Node-Rotten-Potatoes#25]
![image](https://user-images.githubusercontent.com/12772549/46853587-6b6dd400-cdb3-11e8-9545-c83331cea421.png)

Shouldn't this be ` //app.js ` instead of ` //reviews.js`

**Comment by ibirnam** [comment]
added the proper require for app.js in d326bf249e68240c58ee8075804dfa8b5e86bf5c
