### ISSUE TITLE
12. Adding a Route for Comments

### ISSUE THREAD

**Issue by Mintri1199** [MakeSchool-Tutorials/Node-Rotten-Potatoes#26]
Incorrect route creation 

it should be 

const app = require('express')()

// NEW Comment
app.post('/reviews/comments', (req, res) => {
    res.send('reviews comment')
})

module.exports = app

**Comment by ibirnam** [comment]
Good catch, fixed in 9a3bebb6e8be2ad7372bc4998c4fa6fd20aa70a0
