### ISSUE TITLE
1. Making A Plan & Starting an Express.js Project

### ISSUE THREAD

**Issue by campbellmarianna** [MakeSchool-Tutorials/Node-Rotten-Potatoes#27]
In the section, Install Nodemon and Launch Your Server it says "In your terminal you should see "Portfolio App listening on port 3000!" output in your terminal..." while in the prior section we were only suppose to write `console.log('App listening on port 3000!')` according to the code snippet. Overall, I wanted to bring up the fact that is says in one section the message in the console should be "App.." while in the next section it says the message should be "Portfolio App ..."

**Comment by ibirnam** [comment]
It should not say "Portfolio", good catch! Fixed in 96a479e7bacb699c3e8df7727ee08076067bc0aa
