### ISSUE TITLE
Adding timestamps causes exception

### ISSUE THREAD

**Issue by meredithcat** [MakeSchool-Tutorials/Node-Rotten-Potatoes#28]
Under "Displaying 'Created At' Time", the code snippet should read:

```
const Review = mongoose.model('Review', new mongoose.Schema({
  ...
}, {
  timestamps: true
}));
```

https://www.makeschool.com/academy/track/standalone/rotten-potatoes---movie-reviews-with-express-js/bells-and-whistles

**Comment by ibirnam** [comment]
Thanks @meredithcat ! Fixed now in a01d9ffbfb9473dbe14b2adbb0781b613c2f4265
