### ISSUE TITLE
9. Push to Production with Heroku

### ISSUE THREAD

**Issue by edwintcloud** [MakeSchool-Tutorials/Node-Rotten-Potatoes#4]
There are no install instructions for installing the heroku cli in the section titled "SIGN UP FOR AND INSTALL HEROKU". Heroku can be installed using the following command:
```sh
npm i -g heroku
```

**Comment by dacioromero** [comment]
Heroku's documentation [tells Mac users use their installer or use Homebrew](https://devcenter.heroku.com/articles/heroku-cli#download-and-install) and [advises against using the npm method](https://devcenter.heroku.com/articles/heroku-cli#npm). 

I personally used the Homebrew method: `brew install heroku/brew/heroku`

**Comment by edwintcloud** [comment]
Good catch.. homebrew would be the best way to install 100% agree with you there
