### ISSUE TITLE
9. Push to Production with Heroku

### ISSUE THREAD

**Issue by edwintcloud** [MakeSchool-Tutorials/Node-Rotten-Potatoes#5]
For the section titled "ADDING A PRODUCTION DATABASE", the following code must be added to the package.json for heroku to know which file to start with node:
```javascript
"scripts": {
  "start": "node app.js"
}
```

**Comment by edwintcloud** [comment]
It is also necessary to add the following to the package.json for Heroku Deployment.
```javascript
"scripts": {
  "start": "node app.js"
}
```

**Comment by ajbraus** [comment]
added fixed!
